fragment Project on Project {
  id
  title
  status_project
  due_date
  description
  total_time_spent
  start_date
  end_date
  due_date
  owner {
    id
    first_name
    last_name
    avatar
  }
  tasks {
    id
    title
    status_task
    user {
      id
      avatar
      first_name
    }
  }
  users {
    id
    first_name
    last_name
    avatar
    role
  }
}
