fragment Project on Project {
  id
  title
  status_project
  due_date
  owner {
    avatar
  }
  tasks {
    id
    title
    status_task
    user {
      id
      avatar
      first_name
    }
  }
  users {
    id
    avatar
    first_name
    last_name
  }
}
