query GetManagerProjects($where: ProjectWhereInput) {
  projects(where: $where) {
    id
    title
    status_project
    due_date
    description
    total_time_spent
    start_date
    end_date
    is_disabled
    due_date
    project_owner_id
  }
}
