query GetAllNotifications(
  $where: NotificationWhereInput!
  $orderBy: [NotificationOrderByWithRelationInput!]
) {
  notifications(orderBy: $orderBy, where: $where) {
    id
    title
    status
    type
    reference_id
    sender {
      id
      first_name
      last_name
      email
      avatar
    }
    content
    created_at
    updated_at
  }
}
